### ISSUE TITLE
Building using Nix fails for GHC: 7.10.3 & 8.0.2

### ISSUE THREAD

**Issue by mankyKitty** [qfpl/waargonaut#11]
Build fails for the following reason:

```
Configuring concurrent-output-1.10.4...
Setup: At least the following dependencies are missing:
process >=1.6.0 && <1.7.0
```
Not sure if this is a straight forward fix as `process` doesn't exist in `haskell.packages.ghc7103` due to being a boot library for GHC (https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory). So overriding it causes more terrible errors.

Waargonaut happily builds for these versions of GHC when nix isn't involved (see TravisCI). 

My nix skills aren't enough for this, so help would very much be appreciated.

**Comment by puffnfresh** [comment]
nixpkgs hasn't supported 7.10 for a while :crying_cat_face: 

You can maybe use my etaPackages stuff instead, since Eta is (mostly) a fork of 7.10

**Comment by mankyKitty** [comment]
Thanks for the tip! I'll check it out. 

Moving forward I think there's a case for Waargonaut no longer supporting any GHC below 8. So, we'll see.
