### ISSUE TITLE
Readme code would not compile

### ISSUE THREAD

**Issue by etorreborre** [qfpl/waargonaut#16]
Ok, this is a pedantic issue, I'm not sure how you feel about it. The readme should rather say
```
The data structures, parser, and printer are built to comply with the following *pseudo* properties
```
Since `parse . print` is more akin to `Right` rather than `id` :-)

**Comment by mankyKitty** [comment]
Pedantry is acceptable, I'm trying to build a toolkit that lets you be explicit and precise after all. :+1: 

I don't consider it a pseudo property, it is merely expressed using pseudo code. But fair to say that I should add more information around what that statement actually implies?

**Comment by mankyKitty** [comment]
Pushed  3d8a7b5 Let me know if this satisfies your desire for accuracy! :)
