### ISSUE TITLE
Use of Natural (from Numeric.Natural) is unsafe

### ISSUE THREAD

**Issue by jkachmar** [qfpl/waargonaut#23]
Waargonaut's movement code uses `Natural` from `Numeric.Natural`, which doesn't actually enforce that a number is natural via the type system, but rather throws an impure arithmetic exception when provided with negative input.

Reproduction:
```
λ> :i manyMoves
manyMoves ::
  Monad m => GHC.Natural.Natural -> (b -> m b) -> b -> m b
  	-- Defined at /Users/jkachmar/code/waargonaut/src/Waargonaut/Decode.hs:215:1
λ> manyMoves (-1) undefined undefined
*** Exception: arithmetic underflow
```

**Comment by mankyKitty** [comment]
It seems I introduced an unnecessary complication, as `replicate` simply won't for negative inputs.

```
λ> replicate (-3) 'a'
""
λ> replicate 3 'a'
"aaa"
```

I don't see a huge problem in making that type `Int` to match the `replicate` type.

**Comment by tonymorris** [comment]
Also,

[`replicate`](https://hackage.haskell.org/package/natural-0.3.0.2/docs/src/Natural.html#replicate)

**Comment by tonymorris** [comment]
All useful libraries depend on `lens` :)
