### ISSUE TITLE
Waargonaut.Decode.either's document or implementation maybe wrong

### ISSUE THREAD

**Issue by tshinohara** [qfpl/waargonaut#43]
Hi, thank you for creating this library!
I just started learning it and I like it.

Reading through `Waargonaut.Decode` module, I realized that the `either` function attemps the Left decoder first, even though the document states "Right decoder is attempted first.".

For example:
```haskell
> D.simpleDecode (D.either D.scientific D.int) parseBS "123"
Right (Left 123.0)
```
If the Right decoder is attempted first, the result should be `Right (Right 123)`.

**Comment by mankyKitty** [comment]
Argh, good catch. Seems like I didn't keep the ordering after I implemented the `Alt` instance. https://github.com/qfpl/waargonaut/blame/31f00153c1c1d0cda19e906cc8bccf587ddf7f1d/src/Waargonaut/Decode.hs#L759 

Glad you like the library!
