### ISSUE TITLE
Restrictive upper bounds for generics-sop-0.40.1

### ISSUE THREAD

**Issue by jkachmar** [qfpl/waargonaut#52]
Waargonaut currently has a strict upper bound on `generics-sop` that prevents it from using the latest version (and thereby restricting Waargonaut from being used with `servant-0.15`).

**Comment by mankyKitty** [comment]
Bugger. Part of the reason for that particularly restrictive upper bound was that newer versions of `generics-sop` do not build for older GHCs. I don't recall the specifics, I'll have to do some spelunking.

**Comment by jkachmar** [comment]
How important is ongoing GHC 7.10.3 support for `waargonaut`? Looks like [`generics-sop-0.3.2.0` was tested from 7.8.4 -> 8.3.*](https://github.com/well-typed/generics-sop/blob/1225ad81cdf19b58cd39ccd4b5f32c9c7d3624ed/generics-sop.cabal#L40) whereas [`generics-sop-0.4.0.0` is tested from 8.0.2 -> 8.6.2](https://github.com/well-typed/generics-sop/blob/master/generics-sop/generics-sop.cabal#L45).
